=== TechWEb/Tecweb-codice/XML/studio.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="" elementFormDefault="qualified">

	<xsd:element name="office">
		<xsd:complexType>
			<xsd:sequence>
			
				<xsd:element name="story" type="xsd:string"/>
				
				<xsd:element name="composition">
					<xsd:complexType>
						<xsd:sequence minOccurs="0" maxOccurs="unbounded">
							
							<xsd:element name="employee">
								<xsd:complexType>
										<xsd:sequence>
											
											<xsd:element name="name" type="xsd:string"/>
														
											<xsd:element name="pubblications">
												<xsd:complexType>
													<xsd:sequence minOccurs="0" maxOccurs="unbounded">	
														<xsd:element name="pubblication">
															<xsd:complexType>
																<xsd:simpleContent>
																	<xsd:extension base="xsd:string">
																		<xsd:attribute name="n" type="xsd:positiveInteger"/>
																		<xsd:attribute name="date" type="xsd:date"/>
																	</xsd:extension>
																</xsd:simpleContent>
															</xsd:complexType>
														</xsd:element>
													</xsd:sequence>								
												</xsd:complexType>
											</xsd:element>
											
										<xsd:element name="contacts">
												<xsd:complexType>
													<xsd:sequence>	
														<xsd:element name="email" type="xsd:string"/>
														<xsd:element name="linkedin" type="xsd:string"/>
													</xsd:sequence>								
												</xsd:complexType>
											</xsd:element>
											
											<xsd:element name="curriculum" type="xsd:string"/>
											
										</xsd:sequence>								
										
										<xsd:attribute name="title" type="xsd:string"/>
										
								</xsd:complexType>
							</xsd:element>
						
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				

				<xsd:element name="competenceAreas">
					<xsd:complexType>
						<xsd:sequence minOccurs="0" maxOccurs="unbounded">
							
							<xsd:element name="area">
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute name="name" type="xsd:string"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
						
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>				
				
				
				
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== TechWEb/Tecweb-codice/XML/studio.xml
<?xml version="1.0" encoding="UTF-8"?>

<office xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:schemaLocation="C:\Users\User\Documents\Unipd\Tecnologie Web\Progetto\XML\studio.xsd">
	
	<story></story>
	
	
	<composition>
		
		<employee title="">
			<name></name>
			
			<pubblications>
				<pubblication n="1" date="2012-12-05"></pubblication>
				<pubblication n="2" date="2012-12-05"></pubblication>
			</pubblications>
			
			<contacts>
				<email></email>
				<linkedin></linkedin>
			</contacts>
			
			<curriculum></curriculum>
			
		</employee>
		
	</composition>
	
	
	<competenceAreas>
	
		<area name=""></area>
		<area name=""></area>
	
	</competenceAreas>


</office>
